### ISSUE TITLE
Incorrect file rotation occurs when running more than once a day.

### ISSUE THREAD

**Issue by Vikontrol** [nixys/nxs-backup#20]
Hello, I have backups collected once an hour, so there are 24 backups per day on the server. However, if you specify:

```
retention:
      days: 1
      weeks: 1
      months: 0
```

Then when nxs-backup is launched, it will delete all backups from the previous day and start collecting them again one by one. If you set:

```
retention:
      days: 2
      weeks: 1
      months: 0
```
then at any given moment, I will have 48 backups, which is too many for me as it fills up my partition.

If you set safety_backup to true, then backups will only be deleted after a copy is collected, but in that case, at a certain moment, I can only have one backup.

I need to keep backups for the last 24 hours. I couldn't find a parameter that would allow me to do this.

**Comment by randreev1321** [comment]
Hi, @Vikontrol.

Thanks for your interest in nxs-backup.

After studying the problem with our colleagues, we decided to add an additional parameter to the retention settings, which would change the logic of working with backups, leaving the number of copies in rotation rather than the period.

Thus, if you want to keep the last 24 copies, regardless of their creation date, you can use the following retention config:

```yaml
retention:
  count_instead_of_period: true
  days: 24
  weeks: 1
  months: 0
```

A feature has been added to PR #31 and will be released in an upcoming release.

New questions and suggestions are welcome.
