### ISSUE TITLE
Error when working with the count_instead_of_period parameter

### ISSUE THREAD

**Issue by Vikontrol** [nixys/nxs-backup#34]
```
nxs-backup --version
nxs-backup v3.3.0
```
I used the parameter count_instead_of_period true:
```
storages_options:
  - storage_name: local
    backup_path: /var/nxs-backup/dump
    retention:
      count_instead_of_period: true
      days: 24
      weeks: 1
      months: 0
  - storage_name: remote
    backup_path: /var/nxs-backup/dump
    retention:
      count_instead_of_period: true
      days: 24
      weeks: 1
      months: 0
```

nxs-backup deleted my only weekly copies, but with daily ones everything is ok - 24)
