### ISSUE TITLE
Incorrect number of backups

### ISSUE THREAD

**Issue by Vikontrol** [nixys/nxs-backup#44]
Hello

Version:
`nxs-backup 3.6.1`

With the following settings:

```
    backup_path: /var/nxs-backup/dump                                                                                       
    retention:                                                                                                                
      days: 2                                                                                                                 
      weeks: 2                                                                                                                
      months: 0
```
One more backup is actually being created than necessary, i.e., there are 3:

```
/var/nxs-backup/dump/psql/dev1_example_db/daily#
5.8G    dev1_example_db_2024-06-03_03-00.sql
5.7G    dev1_example_db_2024-06-05_03-00.sql
5.7G    dev1_example_db_2024-06-04_03-00.sql
```
