### ISSUE TITLE
Аdd the ability to disable backup rotation

### ISSUE THREAD

**Issue by Dzalgz** [nixys/nxs-backup#45]
Hello!

I use nxs-backup to collect backups in s3 storage. There was a need to change the user role to storage.uploader. I configured backup rotation at the storage level, but now I get errors about the impossibility of deleting old backups. As a temporary solution, I changed the configuration to the following:

```
 retention:
 days: 365
 weeks: 52
 months: 12
```
