### ISSUE TITLE
Remake the s3 url

### ISSUE THREAD

**Issue by Ichthyony** [nixys/nxs-backup#69]
It is necessary to make a more flexible url formation for accessing s3

**Current config**
```
storage_connects:
  - name: s3_store
    s3_params:
      bucket_name: bucket_name
      access_key_id: access_key_id
      secret_access_key: secret_access_key
      endpoint: 'obs.ru-moscow-1.hc.sbercloud.ru'
```
      
In this case, we get a url of the Path-style type - obs.ru-moscow-1.hc.sbercloud.ru/**bucket-name**/object.name
Now the provider is changing the s3 address to Virtual-hosted-style, which implies a different url construction
Virtual-hosted-style - **bucket-name**.obs.ru-moscow-1.hc.sbercloud.ru/object.name

When trying to change the endpoint and add bucket_name to it, the final url is formed incorrectly and we get the error 
```
exec error: Some of backups failed with next errors:
1 error occurred:
 * exit status 2
```
