### ISSUE TITLE
issue with rotation s3

### ISSUE THREAD

**Issue by JoJoBizarrio** [nixys/nxs-backup#79]
We have below settings:

```
  - storage_name: s3 - its yandex.cloud
    backup_path: nxs-backup/path
    retention:
      days: 1
      weeks: 0
      months: 1
```

, but instead of delete yesteday copy nxs-backup try delete day before yesterday, for example:

today is 11-08-2024, nxs-backup removed 09-08-2024:
INFO [**2024-08-11** 03:44:05.044][jobName-desc-files](s3) File 'nxs-backup/path/daily/name_**2024-08-09**_05-51.tar.gz' going to be deleted

so we have rotation, like:

```
  - storage_name: s3
    backup_path: nxs-backup/path
    retention:
      days: 2
      weeks: 0
      months: 2
```

also logs havent notes about removing monthly copies

```
grep -r nxs-backup/path/monthly | wc -l
0
```
